apiVersion: v1
kind: Service
metadata:
  name: {{ include "i2g-operator.fullname" . }}--metrics
  labels:
    {{- include "i2g-operator.labels" . | nindent 4 }}
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    {{- include "i2g-operator.selectorLabels" . | nindent 4 }}
